#!/bin/bash
# from ~/Dropbox/write/darkness/yodrew.github.io/

# collect images
cd img
rsync -auv book-cover.png ../../darkroom-retreat-zip/
rsync -auv photo/*.jpg ../../darkroom-retreat-zip/photo
# rsync -auv photo/book/*.jpg ../../darkroomretreat/manuscript/images
rsync -auv plan/*.pdf ../../darkroom-retreat-zip/plan
rsync -auv plan/source/*.svg ../../darkroom-retreat-zip/plan/source
cd ../
zip -r darkroom-retreat ../darkroom-retreat-zip/
echo -zip done

