#!/bin/bash

# sed -i '2s/"//g' *.md
# sed -i '3s/---/layout: page\
# ---/g' *md
# sed -i 's/kind: article/layout: post/g' *.md

sed -i 's/^created_at:/date:/g' *.md
sed -i '/^tags:/d' *.md
sed -i '/^category:/d' *.md
sed -i '/^published: true/d *.md

sed -i '/^date:/d' 2009-2-23-welcome.md